version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fitness_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness
      MYSQL_USER: fitness_user
      MYSQL_PASSWORD: fitness_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
